name: CI/CD Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test

    steps:
      - name:  Baixar código
        uses: actions/checkout@v4

      - name:  Configurar cache do pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name:  Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name:  Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 bandit

      - name:  Rodar testes com Pytest
        run: pytest --maxfail=1 --disable-warnings -q
